name: Build package

on: [workflow_dispatch]

permissions: write-all

env:
  PACKAGE_NAME: airsaned
  BUILD_TARGET: 23.05.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
   
    - name: Initialize environment
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev \
        file wget

    - name: Install sdk
      run: |
        cd $GITHUB_WORKSPACE
        mv .config .config.bak
        wget https://downloads.openwrt.org/releases/$BUILD_TARGET/targets/mvebu/cortexa9/openwrt-sdk-$BUILD_TARGET-mvebu-cortexa9_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz
        tar -xhf openwrt-sdk-*.tar.xz
        rsync -a openwrt-sdk-$BUILD_TARGET-mvebu-cortexa9_gcc-12.3.0_musl_eabi.Linux-x86_64/* .
 
    - name: Update feeds
      run: cd $GITHUB_WORKSPACE && ./scripts/feeds update -a
     
    - name: Install feeds
      run: cd $GITHUB_WORKSPACE && ./scripts/feeds install -a
       
    - name: Make defconfig
      run: |
        cd $GITHUB_WORKSPACE
        mv .config.bak .config
        make defconfig

    - name: Compile package
      run: cd $GITHUB_WORKSPACE && make -j$(nproc) package/$PACKAGE_NAME/compile V=s

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: ${{env.PACKAGE_NAME}}_bin
        path: bin

    - name: Upload files
      uses: maggie44/actions/packages/automatic-releases@built-packages
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-airsaned
        prerelease: false
        title: Latest airsaned
        files: |
          bin/packages/arm_cortex-a9_vfpv3-d16/custom/*.ipk
