name: Build package

on: [workflow_dispatch]

env:
  PACKAGE_NAME: airsaned

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
   
    - name: Initialize environment
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget

    - name: Clone repository
      run: git clone https://github.com/trinidude4/openwrt -b openwrt-21.02 openwrt
     
    - name: Update feeds
      run: cd $GITHUB_WORKSPACE/openwrt && ./scripts/feeds update -a
     
    - name: Install feeds
      run: cd $GITHUB_WORKSPACE/openwrt && ./scripts/feeds install -a
       
    - name: Copy config
      run: cd $GITHUB_WORKSPACE && cp .config $GITHUB_WORKSPACE/openwrt/.

    - name: Make defconfig
      run: cd $GITHUB_WORKSPACE/openwrt && make defconfig  

    - name: Compile toolchain
      run: cd $GITHUB_WORKSPACE/openwrt && make toolchain/compile
     
    - name: Compile linux
      run: cd $GITHUB_WORKSPACE/openwrt && make target/linux/compile
     
    - name: Compile package
      run: cd $GITHUB_WORKSPACE/openwrt && make package/$PACKAGE_NAME/compile

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: ${{env.PACKAGE_NAME}}_bin
        path: openwrt/bin
